### ISSUE TITLE
震惊！江XX和董XX竟是同一人！这其中究竟是……

### ISSUE THREAD

**Issue by sticnarf** [KingsleyXie/ProgrammingWorksCompetition#2]
`studentNo` 竟然不做 UNIQUE 约束

**Comment by KingsleyXie** [comment]
本辣鸡错了

**Comment by KingsleyXie** [comment]
算了这个不改了2333 当时没想那么多

**Comment by KingsleyXie** [comment]
等等 我突然想起来这个问题，因为每个人是允许同时报这两个比赛的所以不能做 UNIQUE 约束
说起来你可能不信 我当时真的有考虑过这个[捂脸]

不过学号和联系方式不做检查 直接用超过所需长度的字符串存倒是确实偷懒了23333

**Comment by sticnarf** [comment]
还是觉得这个表设计很奇怪啊。
如果要设计有多场比赛的话，不应该搞一个competitions的table，再搞一个registrations的table吗？

**Comment by KingsleyXie** [comment]
啊这个 其实我一开始也是这样做的，但是因为需要限制对于每个比赛队名都唯一，然后当时很赶时间所以就没有做处理，直接建两个table了
