### ISSUE TITLE
震惊！广东某高校竟悄悄建立国机二院学院

### ISSUE THREAD

**Issue by Bokjan** [KingsleyXie/ProgrammingWorksCompetition#3]
近日，广东某高校五山校区弄出大新闻，一个名叫“国机二院”的学院在建立4年后突然挂牌面向公众开放。对于此次事件，我们采访了第一批，也就是2013年入学的气象专业的徐嘉诰同学，请他来谈谈对于自己学院悄然运行这么久一事的看法。

欲知事后详情，请持续关注翡翠台新闻栏目。记者张××广州报道。

**Comment by KingsleyXie** [comment]
没有任何的这个意思，将来如果报道上有了偏差你们是要负泽任的。
